server:
  port: 8080

spring:
  profiles:
    active: "dev"

  application:
    name: gift certificates

  config:
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - env
          - info
          - metrics
          - mappings

initial-data:
  records: 0

---
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: "jdbc:postgresql://localhost:5432/stage2module3db?createDatabaseIfNotExist=true"
    username: user
    password: password
#  jpa:
#    show-sql: true

#    hibernate:
#      ddl-auto: create

logging:
  level:
    com.epam.esm.epammodule3.service: DEBUG

initial-data:
  records: 0