server:
  port: 8080

spring:
  profiles:
    active: "dev"

  application:
    name: gift certificates

  config:
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - env
          - info
          - metrics
          - mappings
