spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: "jdbc:postgresql://localhost:5432/stage2module3db?createDatabaseIfNotExist=true"
    username: user
    password: password
#  jpa:
#    show-sql: true

#    hibernate:
#      ddl-auto: create

logging:
  level:
    com.epam.esm.epammodule3.service: DEBUG

initial-data:
  records: 0
