server:
  port: 8080

spring:
  application:
    name: gift certificates

  datasource:
    url: "jdbc:postgresql://localhost:5432/stage2module3db?createDatabaseIfNotExist=true"
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#    hibernate:
#      ddl-auto: create

    properties:
      hibernate:
        jdbc:
          time_zone: UTC

#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - health
#          - beans
#          - env
#          - info
#          - metrics
#          - mappings
